

run:c cpp java
	bash hello.sh
	ruby hello.rb
	node hello.js
	python hello.py
	groovy hello.groovy
	
c:
	gcc hello.c -o helloc
	./helloc
	rm helloc -f

cpp:
	g++ hello.cc -o hellocc
	./hellocc
	rm hellocc -f

java:
	javac Hello.java
	java Hello
	rm Hello.class -f


